### ISSUE TITLE
Feature request: Support Add and Sub operations

### ISSUE THREAD

**Issue by matthiasbeyer** [neosmart/prettysize-rs#1]
Hi.

Would be useful to be able to add and subtract values, wouldn't it?

Note that you might not only want to add implementations for `Add`, `AddAssign`, `Sub` and `SubAssign` , but maybe also safe implementations for adding one byte to 1000 exabyte ... which would overflow I guess.

**Comment by mqudsi** [comment]
Thanks for chiming in. Yes, this would be helpful, since it would reduce the current syntax from

```rust
let size3 = Size::Bytes(size1.bytes() + size2.bytes());
```

to 

```rust
let size3 = size1 + size2;
```

Which is a lot nicer :)

We already use the `num_traits` crate, which features the [`NumOps`](https://docs.rs/num-traits/0.2.6/num_traits/trait.NumOps.html) trait we can implement.

**Comment by mqudsi** [comment]
This is implemented in `size` 0.2+

Lengthy discussion on why this wasn't as easy as I first thought:
https://neosmart.net/blog/2022/prettysize-0-3-release-and-a-weakness-in-rusts-type-system/

**Comment by mqudsi** [comment]
Just documenting here that `AddAssign` and co are intentionally not implemented as `Size` is (at least until someone provides a good reason otherwise) an immutable type.

**Comment by matthiasbeyer** [comment]
I agree that having an immutable type is a good idea, no need for `AddAssign` etc.! Thanks for shipping this!

**Comment by mqudsi** [comment]
Cheers!

**Comment by vic1707** [comment]
Hello, first, thx for the crate.

I think I have a use case for `AddAssign`, i'm making a tool which is at some point calculating the size of a folder.
The size of a folder is basically `0 B` + the sum of all the files and folders sizes inside it, I calculate it recursively and my current code requires me to reassign a size each time I encounter a new child file of folder.

I'm new to Rust and I tried to implement `AddAssign` myself but encountered the rustc[E0117](https://doc.rust-lang.org/error-index.html#E0117).

for now I'm using a `fn` that looks like this
```rs
fn add_size(&mut self, size: Size) {
  self.size = Size::from_bytes(self.size.bytes() + size.bytes());
}
```
It works but having the `AddAssign` & co traits would be nice if you're okay with it 😁.

**Comment by mqudsi** [comment]
@vic1707 thanks for dropping by. Yeah, since `Size` an immutable type you would need to reassign it each time instead of using `+= other`, but you don't need to spell it out like that. You can just do

```rust
fn add_size(&mut self, size: Size) {
    self.size = self.size + size;
}
```

Since the `Add<Size>` trait is already implemented.

**Comment by vic1707** [comment]
yup, mybad for this terrible snippet of code 😅

**Comment by mqudsi** [comment]
No apologies needed! My thinking is that with the `Add` trait (like I showed above), it's short enough to drop the function altogether so you can just update the size as you go along:

```rust
fn add_dir(&mut self, p: &Path) {
    ....
    let dir_size: Size = ...;
    self.size = self.size + dir_size;
}
```

But it would be nicer with `AddAssign` so maybe we should add that!
