### ISSUE TITLE
Incorrect formatting of values > 1 GB - Base 10 formatting

### ISSUE THREAD

**Issue by teschty** [neosmart/prettysize-rs#2]
Hi, thanks for the library!

There's a problem with formatting caused by an error on [line 17](https://github.com/neosmart/prettysize-rs/blob/98908c5aabac8b98950d0ee7e6a0b891b7bfb12d/src/lib.rs#L17). Where it should be multiplying by `GIGABYTE`, it is instead multiplying by `MEGABYTE`.

**Comment by mqudsi** [comment]
Thanks, @teschty. Nice catch!

How did you find this crate, if you don't mind my asking?

**Comment by mqudsi** [comment]
PrettySize 0.1.2 has been published to crates.io containing the fix: https://crates.io/crates/size

**Comment by teschty** [comment]
Awesome!

Actually just happened to search for "size" on crates.io and it was the first match. Appreciate the quick turnaround!
