### ISSUE TITLE
Implement Serialize, Deserialize, as well as other useful traits

### ISSUE THREAD

**Issue by Antosser** [neosmart/prettysize-rs#6]

**Comment by Antosser** [comment]
I have made 2 PRs to fix this

**Comment by mqudsi** [comment]
I have merged your PR, but there are two issues:

* The build was broken because the serde "deserialize" feature was not included in Cargo.toml
* This is going to deserialize to a struct; it should deserialize to the number of bytes instead (and serialize from the same).

**Comment by mqudsi** [comment]
I added a number of commits that address this feature over the past couple of days. It's conditionally enabled with the `serde` feature (disabled by default). As per my last comment above, the `Size` type serializes/deserializes transparently to/from the number of bytes (and not as its own object). The crate doc and repo README have been updated with the relevant info.

I haven't pushed a new release yet, but it'll go out as version 0.5.0 soon.
